<?php

namespace Backend\APIBundle\Repository;

/**
 * MagazineDealerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineDealerRepository extends \Doctrine\ORM\EntityRepository
{
}
