<?php

namespace Backend\APIBundle\Repository;

/**
 * MagazineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineRepository extends \Doctrine\ORM\EntityRepository
{
    public function reorder($content)
    {
        $em = $this->getEntityManager();

        $count = 0;

        foreach($content as $i => $content_id){
            print_r($content_id);
            $q = $em->createQuery('update BackendAPIBundle:Magazine c set c.isBooked = ?1 where c.id = ?2')
                ->setParameter(1, true)
                ->setParameter(2, $content_id);
            //$jsonDecoded = json_decode($q);
            //var_dump($jsonDecoded);
            //check how many records updated.
            $count += $q->execute();
            //print_r($count);
        }
        return $count;
    }
}
