<?php

namespace Backend\APIBundle\Repository;

/**
 * BookDealerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookDealerRepository extends \Doctrine\ORM\EntityRepository
{
}
